---
title: "Linear Y performance comparison"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
library(magrittr)
library(ggplot2)
```

```{r batch job}
# batchtools::makeRegistry(
#   file.dir = "/n/janson_lab/lab/sma/CompDA_paper/r_batchtools_reg/linear_Y",
#   package = c("magrittr"))
batchtools::loadRegistry(
  file.dir = "/n/janson_lab/lab/sma/CompDA_paper/r_batchtools_reg/linear_Y",
  writeable = TRUE)
rm(list = ls())
```

```{r define job}
dir_output <- "/n/janson_lab/lab/sma/CompDA_paper/results/simulation/linear_Y"
dir.create(dir_output, recursive = TRUE, showWarnings = FALSE)
dir.create(paste0(dir_output, "/fit"), recursive = TRUE, showWarnings = FALSE)
dir.create(paste0(dir_output, "/debug"), recursive = TRUE, showWarnings = FALSE)
dir.create(paste0(dir_output, "/data"), recursive = TRUE, showWarnings = FALSE)

tb_effetSize <- 
  tibble::tibble(
    n_samples = 400,
    n_features = 200,
    signal_density = 0.1,
    effect_size = c(0, 0.05, 0.1, 0.15, 0.2)
  )

tb_sampleSize <- 
  tibble::tibble(
    n_samples = c(50, 100, 200, 400),
    n_features = 200,
    signal_density = 0.1,
    effect_size = 0.15
  )

tb_dimension <- 
  tibble::tibble(
    n_samples = 400,
    n_features = c(50, 100, 200, 300),
    signal_density = 0.1,
    effect_size = 0.15
  )

tb_sigDensity <- 
  tibble::tibble(
    n_samples = 400,
    n_features = 200,
    signal_density = c(0.025, 0.05, 0.1, 0.2),
    effect_size = 0.15
  )

tb_job <- rbind(
  tb_effetSize,
  tb_sampleSize,
  tb_dimension,
  tb_sigDensity) %>%
  dplyr::distinct() %>% 
  tidyr::crossing(r_y = seq(1, 10),
                  r_x = seq(1, 20)) %>% 
  dplyr::mutate(i_job = seq(1, dplyr::n()))

set.seed(0)
tb_job <- tb_job %>% 
  dplyr::mutate(
    seed = ceiling(runif(n = nrow(tb_job), 0, 1) * 1e7)
  )
save(tb_job, 
     file = paste0(dir_output, "/tb_job.RData"))

one_job <- function(i_job) {
  # x data
  load("/n/janson_lab/lab/sma/CompDA_paper/data/simulation/mat_species.RData")
  source("/n/janson_lab/lab/sma/CompDA_paper/R/other_methods.R")
  source("/n/janson_lab/lab/sma/CompDA_paper/R/simulate_y.R")
  source("/n/janson_lab/lab/sma/CompDA_paper/R/helpers.R")
  
  load(paste0(dir_output, "/tb_job.RData"))
  for(ii_job in seq((i_job - 1) * n_job_each + 1, i_job * n_job_each)) {
    i_tb_job <- tb_job[ii_job, ]
    set.seed(i_tb_job$seed)
    
    i_x_obs <- mat_species[sample.int(nrow(mat_species), 
                                      size = i_tb_job$n_features),
                           seq(i_tb_job$n_samples * (i_tb_job$r_x - 1) + 1, 
                               i_tb_job$n_samples * i_tb_job$r_x)] %>% 
      apply(2, tss_withzero) %>% 
      t() 
    
    half_min <- min(setdiff(i_x_obs, 0)) / 2
    y_sim <- simulate_y(x = i_x_obs, 
                        effect_size = i_tb_job$effect_size, 
                        n_signal = i_tb_job$n_features * i_tb_job$signal_density, 
                        epsilon = half_min,
                        seed = ii_job)
    save(y_sim, file = paste0(dir_output, "/data/y_sim_", ii_job, ".RData"))
    
    # CompDA
    time_CompDA <- system.time(
      fit_CompDA <-
        CompDA::CompDA(
          x = i_x_obs, y = y_sim$y, epsilon = half_min,
          family_y = "gaussian", method_y = "glmnet",  m = 1e4,
          debug_dir = NULL)
    )
    
    
    fit_DA <-
      test_DA(
        x = i_x_obs, y = y_sim$y,
        epsilon = half_min,
        debug_path = paste0(dir_output, "/debug/maaslin_", ii_job))
    
    fit_linda <- 
      test_linda(
        x = i_x_obs, y = y_sim$y)
    
    fit_lasso <-
      test_lasso(
        x = i_x_obs, y = y_sim$y,
        family = "gaussian",
        epsilon = half_min)
    
    save(fit_CompDA, file = paste0(dir_output, "/fit/CompDA_", ii_job, ".RData"))
    save(time_CompDA, file = paste0(dir_output, "/fit/time_CompDA_", ii_job, ".RData"))
    save(fit_DA, file = paste0(dir_output, "/fit/DA_", ii_job, ".RData"))
    save(fit_linda, file = paste0(dir_output, "/fit/linda_", ii_job, ".RData"))
    save(fit_lasso, file = paste0(dir_output, "/fit/lasso_", ii_job, ".RData"))
  }
  return(NULL)
}
```

```{r submit jobs}
batchtools::clearRegistry()
n_job_each <- 5
tb_ids <- batchtools::batchMap(one_job,
                               i_job = seq(1, nrow(tb_job) / n_job_each))
batchtools::batchExport(list(dir_output = dir_output,
                             n_job_each = n_job_each))

# Grid parameters
ncpus <- 1
partition <- "janson,janson_cascade,shared"
walltime <- 3600

# test run
batchtools::submitJobs(ids = seq(1, 10),
                       resources =  list(ncpus = ncpus,
                                         partition = partition,
                                         walltime = walltime))
# submit rest of jobs
batchtools::submitJobs(ids = batchtools::findNotSubmitted(),
                       resources =  list(ncpus = ncpus,
                                         partition = partition,
                                         walltime = walltime))
```
