---
title: "When Y model is misspecified"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
library(magrittr)
library(ggplot2)
```

```{r summarize results}
dir_output <- "/n/janson_lab/lab/sma/CompDA_paper/results/simulation/misspecified"
load(paste0(dir_output, "/tb_job.RData"))

tb_results <- 
  tb_job$i_job %>%
  purrr::map_dfr(function(i_job) {
    load(paste0(dir_output, "/data/y_sim_", i_job, ".RData"))
    load(paste0(dir_output, "/fit/tb_fit_", i_job, ".RData"))
    
    tb_fit %>% 
      dplyr::group_split(method) %>% 
      purrr::map_dfr(
        function(i_tb) {
          q <- p.adjust(i_tb$p, method = "BH")
          pos <- q < 0.05
          tibble::tibble(
            power = mean(pos[y_sim$ind_TP]),
            fdr = {
              if(!any(pos))
                0
              else
                sum((!y_sim$ind_TP) & pos) / sum(pos)
            },
            method = i_tb$method[1])
        }) %>% 
      dplyr::mutate(i_job = i_job)
  })
tb_results <- tb_results %>% 
  dplyr::left_join(tb_job, by = "i_job")
save(tb_results, file = paste0(dir_output, "/tb_results.RData"))
```
